esphome:
  name: esp32_test

  libraries:
    - Wire

  
external_components:
    - source:
        type: local
        path: components 

      components: [m5stack_pbhub]

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "update"

ota:
  password: "update"

wifi:
  ssid: "Livebox-36B0"
  password: "4CHfRsdx9C9c8VdH2t"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32 Test Fallback Hotspot"
    password: "ezOUB4lHEavi"

# Configuring the GPIO Hub with Arduino I2C

#Pin numberring in the PbHUB (The first digit is the channel number and the second digit is the pin number)
# CHANNEL 0 : 00 and 01
# CHANNEL 1 : 10 and 11
# CHANNEL 2 : 20 and 21
# CHANNEL 3 : 30 and 31
# CHANNEL 4 : 40 and 41
# CHANNEL 5 : 50 and 51
m5stack_pbhub:
  - id: 'M5Stack_HUB'
    address: 0x61 # I2C Address
    sda: 21 # I2C SDA Pin
    scl: 22 # I2C SCL Pin 

# Link the m5stack_pbhub to a switch 
switch:
  - platform: gpio
    name: "Light on PBHUB Channel #0 pin #0"
    pin:
      m5stack_pbhub: M5Stack_HUB
      # Use pin number 0
      number: 00
      mode:
        output: true
      inverted: false
      
  - platform: gpio
    name: "Pumps on PBHUB Channel #0 pin #1"
    pin:
      m5stack_pbhub: M5Stack_HUB
      # Use pin number 0
      number: 01
      mode:
        output: true
      inverted: false

# Link the m5stack_pbhub to a  binary sensor
binary_sensor:
  - platform: gpio
    name: "Dual Button on PBHUB Channel #2 Pin #0"
    pin:
      m5stack_pbhub: M5Stack_HUB
      # Use pin number 0
      number: 20
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "Dual Button on PBHUB Channel #2 Pin #1"
    pin:
      m5stack_pbhub: M5Stack_HUB
      # Use pin number 0
      number: 21
      mode:
        output: true
      inverted: false


web_server:
  port: 80 

    