esphome:
  name: esp32_test

  libraries:

  
external_components:
    - source:
        type: local
        path: components 

      components: [sonic_i2c]

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "update"

ota:
  password: "update"

wifi:
  ssid: "Bbox-727DF9A6"
  password: "c7HwHdEL33bhCJ4fVm"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32 Test Fallback Hotspot"
    password: "ezOUB4lHEavi"


i2c:
  id: bus_i2c
  sda: 25
  scl: 23
# SONIC I2C sensor configuration

# SONIC I2C sensor configuration
# Can only use one sensor 
sonic_i2c:
   i2c_id: bus_i2c
   address: 0x57
   name: Distance Sensor 2
   unit_of_measurement: mm
   update_interval: 5s

sonic_i2c:
   i2c_id: bus_i2c
   address: 0x57
   name: Distance Sensor
   unit_of_measurement: mm
   update_interval: 5s

web_server:
  port: 80 

    